### ISSUE TITLE
1. Configure the application to maintain 2 additional states

### ISSUE THREAD

**Issue by Nuchaz** [ProjectGroupB/Assignment-5#1]
listings.edit
listings.map

This is the first step in the assignment.

**Comment by morlando18** [comment]
I'll give this one a try

**Comment by Nuchaz** [comment]
I am going to have a go at this since it looks like I need it before I can do much with issues #4 and #5

**Comment by Nuchaz** [comment]
ok, I was successful on this one. I created a PR and merged it.
